#!/usr/bin/env bash
# This script tells a story based on the contents of /etc/passwd

# Read the contents of /etc/passwd line by line
while IFS=: read -r username _ userid _ home_directory shell user_info; do
    echo "The user $username is part of the $userid gang, lives in $home_directory and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd
