#!/usr/bin/env bash

# Grouping visitors by IP and HTTP status code
# and sorting by occurrences in descending order
awk '{print $1, $9}' apache-access.log | 
    awk '{count[$1 " " $2]++} END {for (entry in count) print count[entry], entry}' | 
    sort -nr
