#!/usr/bin/env bash
# Display a list of all currently running processes in a user-friendly format with process hierarchy

# Display process information with a tree structure
ps -e -o user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --sort=pid | head -1
ps -e -o user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --sort=pid --forest
