#!/usr/bin/env bash
# Display a list of all currently running processes in the required format

# Display processes in the correct format with headers
ps -e -o user=USER,pid,pcpu,pmem,vsz,rss,tty,stat,start=STARTED,time,command=COMMAND --sort=pid --forest
