#!/usr/bin/env bash
# shellcheck disable=SC2009
# This script displays lines containing the word 'bash', allowing you to find the PID of your Bash processes.

ps -e -o user,pid,ppid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | grep bash
