#!/usr/bin/env bash

# This script stops the running 4-to_infinity_and_beyond process using the kill command.

# Get the PID of the running 4-to_infinity_and_beyond process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Check if the PID was found
if [ -n "$pid" ]; then
    kill "$pid"
fi
