#!/bin/bash

# 4-to_infinity_and_beyond script
while true; do
    echo "To infinity and beyond"
    sleep 1
    if [ -f "stop_signal" ]; then
        rm "stop_signal"  # Clean up the signal file
        break
    fi
done
echo "Terminated"
